Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using Shipstone.OpenBook.Data;
using Shipstone.OpenBook.Models;
using Shipstone.OpenBook.ViewModels;

namespace Shipstone.OpenBook.Controllers
{
    [Controller]
    public class PostController : Controller
    {
        private readonly Context _Context;
        private readonly ILogger<PostController> _Logger;
        private readonly UserManager<User> _UserManager;

        public PostController(
            ILogger<PostController> logger,
            Context context,
            UserManager<User> userManager
        )
        {
            this._Context = context;
            this._Logger = logger;
            this._UserManager = userManager;
        }

        [Authorize]
        [HttpPost]
        [ProducesResponseType((int) HttpStatusCode.Created)]
        [ProducesResponseType((int) HttpStatusCode.BadRequest)]
        [ProducesResponseType((int) HttpStatusCode.Unauthorized)]
        [Route("api/[controller]")]
        public async Task<IActionResult> ApiCreateAsync(Post model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.BadRequest();
            }

            User user = await this._UserManager.GetUserAsync(this.User);
            StatusViewModel<int> id = await PostDao.CreateAsync(this._Context, user, model);
            this._Logger.LogInformation($"User {user.UserName} created post {id.ViewModel} at {DateTime.UtcNow}");
            return this.Created($"api/Post/{id.ViewModel}", null);
        }

        [HttpGet]
        [ProducesResponseType((int) HttpStatusCode.OK)]
        [ProducesResponseType((int) HttpStatusCode.NotFound)]
        [Route("api/[controller]/{id}")]
        public async Task<IActionResult> ApiRetrieveAsync(int id)
        {
            StatusViewModel<Post> post = await PostDao.RetrieveAsync(this._Context, id);

            if (post.StatusCode == HttpStatusCode.NotFound)
            {
                return this.NotFound();
            }

            return this.Ok(post.ViewModel);
        }

        [ActionName("Create")]
        [Authorize]
        [HttpGet]
        public IActionResult WebCreate() => this.View();

        [ActionName("Create")]
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> WebCreateAsync(Post model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            User user = await this._UserManager.GetUserAsync(this.User);
            StatusViewModel<int> id = await PostDao.CreateAsync(this._Context, user, model);
            this._Logger.LogInformation($"User {user.UserName} created post {id.ViewModel} at {DateTime.UtcNow}");
            return this.RedirectToAction("Details", new { id = id.ViewModel });
        }

        [ActionName("Details")]
        [HttpGet]
        public async Task<IActionResult> WebDetailsAsync(int id)
        {
            StatusViewModel<Post> post = await PostDao.RetrieveAsync(this._Context, id);

            if (post.StatusCode == HttpStatusCode.NotFound)
            {
                return this.NotFound();
            }

            User user = await this._UserManager.GetUserAsync(this.User);

            return this.View(new PostViewModel
            {
                IsCreator = !(user is null) && user.Id == post.ViewModel.CreatorId,
                Post = post.ViewModel
            });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - OpenBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shipstone.OpenBook.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OpenBook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Post" asp-action="Create">Create post</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Christopher Shipstone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>